Пешков Дмитрий
VK-BMSTU-QA/e2e-spring-2022 pull request #11
Opened 2022-04-07 18:54 UTC by DPeshkoff

2022-04-09 12:04 UTC, TonyBlock approved these changes

2022-04-09 12:10 UTC, GeorgiyX requested changes

2022-04-09 12:10 UTC, GeorgiyX commented on test/specs/board_add_member.e2e.ts
> +        });
Кажется нужно спрятать в pageobject

2022-04-09 12:10 UTC, GeorgiyX commented on test/pageobjects/board.page.ts
> +        return await this.modalAddMemberSearchResultUsername.getText();
Сюда не нужно добавить `waitForDisplayed`?

2022-04-09 12:10 UTC, GeorgiyX commented on test/pageobjects/board.page.ts
> +    public async fillModalSettings (name?: string, description?: string) {
`description` не используется

2022-04-09 12:10 UTC, GeorgiyX commented on test/pageobjects/board.page.ts
> +    public get modalAddMemberSearchResultUsername () {
Не очень очевидно что это первый div с user name, мб `divFirstAddMemberSearchResult`?

2022-04-09 12:10 UTC, GeorgiyX commented on test/pageobjects/board.page.ts
> +    }
Ага, выглядит хардкодно.

2022-04-09 12:10 UTC, GeorgiyX commented on test/pageobjects/board.page.ts
> +    public get divColumnHeaderTitle () {
Не очень очевидно что это первая колонка (мб стоит добавить First в название или сделать селектор динамическим, чтобы произвольную колонку получать).

2022-04-09 12:10 UTC, GeorgiyX commented on test/specs/board_rename.e2e.ts
> +        oldBoardName = await BoardPage.lblBoardName.getText();
Думаю стоит логику получения значения внутри pageobject, а также дополнительно вызывать `waitForDisplayed`.

2022-04-09 12:10 UTC, GeorgiyX commented on test/specs/board_modal_window_create_column.e2e.ts
> +        data_id = await BoardPage.divColumn.getAttribute('data-id');
Стоит скрыть в pageobject логику получения атрибута.

2022-04-09 12:10 UTC, GeorgiyX commented on test/specs/board_tag_add.e2e.ts
> +        const testTagName = await BoardPage.modalTagName.getText();
Тоже что и в `board_rename.e2e.ts`: думаю стоит логику получения значения скрыть внутри pageobject, а также дополнительно вызывать `waitForDisplayed`.

2022-04-09 13:26 UTC, GeorgiyX approved these changes

2022-04-09 14:46 UTC, GeorgiyX approved these changes

2022-05-03 10:26 UTC, VictoriaOtm commented on test/pageobjects/board.page.ts
> +    // Модальное окно добавления пользователей в доску
кажется получился весьма перегруженный page, очень объемный. Page Object - это не обязательно про страницу в чистом виде, можно делить на pages даже по отдельным модальным окнам, по сути как раз то, что ты разделил комментами, можно было бы вынести в отдельные pages и объединить в одном board.pages.ts

2022-05-29 13:45 UTC, closed without merging