Беляев Леонид
VK-BMSTU-QA/e2e-spring-2022 pull request #13
Opened 2022-04-07 18:59 UTC by 23-yo-designer-from-san-francisco

Логин, главная, плеер, поиск

2022-04-08 18:27 UTC, frbgd requested changes

2022-04-08 18:27 UTC, frbgd commented on test/pageobjects/login.page.ts
> +        return $('#auth-form > input:nth-child(1)');
селекторы поконкретнее

2022-04-08 18:27 UTC, frbgd commented on test/pageobjects/profile.page.ts
> +        return $('#content > div > div.profile-page__content > form.profile-form > div:nth-child(2) > input');
cелектор поконкретнее

2022-04-08 18:27 UTC, frbgd commented on test/specs/firstalbum.main.e2e.ts
> +// // Тут что-то пошло не так, не успел доделать
доделай

2022-04-08 18:27 UTC, frbgd commented on test/specs/search.empty.e2e.ts
> +        SearchPage.setWindowSize(1400, 1200);
тут тогда тоже через переменные укажи размеры окна

2022-04-09 10:31 UTC, frbgd approved these changes

2022-04-09 10:42 UTC, just4n4cc approved these changes
все ровно!

2022-05-03 11:29 UTC, VictoriaOtm commented on test/pageobjects/main.page.ts
> +    public async playFirstTrack() {
кажется получился немного перегруженный page, объемный. Page Object - это не обязательно про страницу в чистом виде, можно делить на pages даже по отдельным модальным окнам. Если мы в MainPage положим вообще все, что есть у вас на главной, будет совсем грустно, подумай, на какие элементы можно разделить

2022-05-03 11:29 UTC, VictoriaOtm commented on test/specs/firstalbum.main.e2e.ts
> +        MainPage.setWindowSize(screenWidth, screenHeight);
достаточно вызывать один раз

2022-05-03 11:31 UTC, VictoriaOtm commented on test/pageobjects/main.page.ts
> +    public async playFirstTrack() {
кстати можно разделенные элементы потом сделать public полями класса MainPage, что будет соответствовать логике страницы, просто код будет аккуратно разнесен по разным местам

2022-05-04 19:04 UTC, 23-yo-designer-from-san-francisco commented
Тесты все еще проходят :)
<img width="524" alt="image" src="https://user-images.githubusercontent.com/42890090/166807622-707d15bd-c1d3-4692-8a42-319ba0672457.png">

2022-05-29 13:41 UTC, closed without merging