Написать 4 e2e теста
VK-BMSTU-QA/e2e-spring-2022 pull request #14
Opened 2022-04-07 18:59 UTC by TonyBlock

Скорее всего работают все 4 теста, однако проверить не представляется возможным из-за нехватки времени и ошибки с портами

2022-04-07 19:18 UTC, TonyBlock commented
Пришлось отдельно обновлять тестовый репорт из-за внезапной проблемы с портами

2022-04-09 07:53 UTC, 23-yo-designer-from-san-francisco approved these changes

2022-04-09 07:53 UTC, 23-yo-designer-from-san-francisco commented on test/pageobjects/login.page.ts
> +    public get btnEnter () {
Я бы все-таки назвал `btnLogin`, немного сбивает с толку, как будто проверяется нажатие Enter, а не клик по кнопке

2022-04-09 12:13 UTC, DPeshkoff requested changes

2022-04-09 12:13 UTC, DPeshkoff commented on test/specs/createBoard.e2e.ts
> +        const expectedBoardName = 'someBoard'
;

2022-04-09 12:13 UTC, DPeshkoff commented on test/specs/createTeam.e2e.ts
> +        const expectedTeamName = 'someTeam'
;

2022-04-09 12:17 UTC, DPeshkoff approved these changes

2022-05-03 10:39 UTC, closed without merging