Клонов Александр
VK-BMSTU-QA/e2e-spring-2022 pull request #4
Opened 2022-04-07 18:01 UTC by Shureks-den

2022-04-08 22:48 UTC, BUSH1997 commented on test/specs/publish.volchock.ts
> +        await MainPage.getUsername();
А зачем в этом тесте эта проверка?

2022-04-08 22:48 UTC, BUSH1997 commented on test/specs/search.volchock.ts
> +            `Происходит поиск по тексту "${gotSearchText}", введеному в текстовый инпут "${expectedSearchText}"`,
 1. Наверное "поисковый инпут"
 2. Не очень понимаю смысл этого сообщения. Мне казалось сообщение в strictEqual должно как-то указывать на ошибку, типа "Результат поиска по тексту "${gotSearchText}" не совпадает с ожидаемым "${expectedSearchText}""

2022-04-08 22:52 UTC, BUSH1997 requested changes

2022-04-08 22:52 UTC, BUSH1997 commented on test/specs/publish.volchock.ts
> +        await MainPage.getUsername();
А зачем в этом тесте эта проверка?

2022-04-08 22:52 UTC, BUSH1997 commented on test/specs/search.volchock.ts
> +            `Происходит поиск по тексту "${gotSearchText}", введеному в текстовый инпут "${expectedSearchText}"`,
 1. Наверное "поисковый инпут"
 2. Не очень понимаю смысл этого сообщения. Мне казалось сообщение в strictEqual должно как-то указывать на ошибку, типа "Результат поиска по тексту "${gotSearchText}" не совпадает с ожидаемым "${expectedSearchText}""

2022-04-09 06:26 UTC, Shureks-den commented on test/specs/publish.volchock.ts
> +        await MainPage.getUsername();
Нужна чтобы дождаться авторизации, иначе если мы попытаемся создать объявление NewAdvPage.open нас обратно в авторизацию перекинет

2022-04-09 09:58 UTC, GeorgiyX requested changes

2022-04-09 09:58 UTC, GeorgiyX commented on test/pageobjects/main.page.ts
> +        await this.modalButton.click();
Тут не нужно `waitForDisplayed`?

2022-04-09 09:58 UTC, GeorgiyX commented on test/pageobjects/profile.page.ts
> +        return $('.profile-content-right__ads-type=Архив');
На семинаре вроде говорили, что в селекторе опасно привязываться к тексту элемента (т.к. например если у сайта появится локализация, то тесты сломаются). Можно использовать `.profile-content_right > span:nth-of-type(2)`.

2022-04-09 10:07 UTC, GeorgiyX approved these changes

2022-04-09 10:56 UTC, BUSH1997 approved these changes

2022-05-03 11:58 UTC, closed without merging