Ветошкин Артём
VK-BMSTU-QA/e2e-spring-2022 pull request #7
Opened 2022-04-07 18:23 UTC by ThCompiler

2022-04-08 22:02 UTC, Flash1ee commented on test/pageobjects/signup.page.ts
> +    public get inputUsername () {
используй `private` методы, если они локальные, а они локальные

2022-04-08 22:02 UTC, Flash1ee commented on test/specs/singup_short_nickname.e2e.ts
> +        const email = generate_string(10) + '@mail.ru';
вынеси тогда @mail.ru в константу, используется не единожды

2022-04-08 22:02 UTC, Flash1ee commented on test/utilits.ts
> +const generate_string = (len) : string => {
придерживайся стиля. если везде camel case, то используй его везде

2022-04-08 22:02 UTC, Flash1ee commented on test/utilits.ts
> +    return [ ...Array(len) ].map(() => (~~(Math.random() * 36)).toString(36)).join('');
36 - магическое число, сделай константой

2022-04-09 13:35 UTC, Flash1ee commented
аппрув

2022-04-09 13:36 UTC, Flash1ee approved these changes

2022-04-09 13:40 UTC, DPeshkoff requested changes

2022-04-09 13:40 UTC, DPeshkoff commented on test/specs/singup_empty_email.e2e.ts
> +        assert.strictEqual(await SignupPage.checkErrorEmail(), true);
Можно еще добавить сообщение

2022-04-09 13:40 UTC, DPeshkoff commented on test/specs/singup_exists_username.e2e.ts
> +        assert.strictEqual(await SignupPage.checkMainError(), true, 'No message about repeat username');
Плохо, когда у сообщений разный стиль и язык

2022-04-09 13:40 UTC, DPeshkoff commented on test/specs/singup_short_nickname.e2e.ts
> +    it('should signup with valid credentials', async () => {
should или should not?

2022-04-09 14:20 UTC, DPeshkoff approved these changes

2022-05-03 11:54 UTC, closed without merging