Кучерявенко Алексей
VK-BMSTU-QA/e2e-spring-2022 pull request #8
Opened 2022-04-07 18:39 UTC by frbgd

тест на логин, тест на переименовывание плейлиста, тест на добавление в избранное

2022-04-08 23:05 UTC, BUSH1997 requested changes

2022-04-08 23:05 UTC, BUSH1997 commented on test/pageobjects/login.page.ts
> +        return $('#content > div > div.profile-page__content > form.profile-form > div:nth-child(2) > input');
Это самый короткий возможный селектор?) если да, то ок, что поделаешь

2022-04-08 23:05 UTC, BUSH1997 commented on test/specs/favorites.e2e.ts
> +        const track = await FavoritesPage.getTrack(trackId);
А если пришел  null из-за того, что элемент не прогрузился еще? Возможно стоит добавить в getTrack() await this.getTrackImg.waitForDisplayed() или что-то в этом роде

2022-04-08 23:05 UTC, BUSH1997 commented on test/specs/playlist.e2e.ts
> +describe('Login with correct username and password', () => {
У тебя почти везде в describe и it описание теста на английском, а в assert ошибка на русском. Думаю, стоит выбрать что-то одно

2022-04-09 08:01 UTC, 23-yo-designer-from-san-francisco requested changes

2022-04-09 08:01 UTC, 23-yo-designer-from-san-francisco commented on test/pageobjects/favorites.page.ts
> +export default new FavoritesPage('https://lostpointer.site');
Нет новой строки в конце файла =|

2022-04-09 08:01 UTC, 23-yo-designer-from-san-francisco commented on test/pageobjects/login.page.ts
> +        return $('#app > div.app__content > div.main-layout > div.topbar > span > div > a');
**Можно** короче

2022-04-09 08:01 UTC, 23-yo-designer-from-san-francisco commented on test/pageobjects/login.page.ts
> +        return $('#content > div > div.profile-page__content > form.profile-form > div:nth-child(2) > input');
Тоже **можно** короче

2022-04-09 08:01 UTC, 23-yo-designer-from-san-francisco commented on test/pageobjects/playlist.page.ts
> +    public get playlistAvatar () {
Тут и ниже почти везде, если не везде, можно убрать все `>` и все, что перед ними

2022-04-09 11:44 UTC, 23-yo-designer-from-san-francisco approved these changes

2022-04-09 12:26 UTC, BUSH1997 approved these changes

2022-05-03 11:33 UTC, VictoriaOtm commented on test/pageobjects/album.page.ts
> +        return super.open('album/456');
почему открываем конкретный альбом? давай передавать id альбома из теста, чтобы был универсальный метод

2022-05-03 11:33 UTC, VictoriaOtm commented on test/pageobjects/playlist.page.ts
> +        return super.open('playlist/198');
аналогично

2022-05-29 13:42 UTC, closed without merging